### PR TITLE
Added Functionality For Restaurant Requests (Also Functionality In Pantry)

### PR DESCRIPTION
**Pull request by Skull0025**
This opens a huge door for possibilities for restaurant requests!

### CODE REVIEW

**Comment by SketchMaster2001** [comment]
Right of the bat, some of your code will not work in production. The way you handle the response will not work because it is encoded in shift-jis. 

Secondly, I noticed you just copy and pasted some of our code from room server for no apparent reason? 

Third of all, we aren't looking to implement this in the way that you are doing.

**Comment by lambda-makes-things** [comment]
> Secondly, I noticed you just copy and pasted some of our code from room server for no apparent reason?
speaking of which ???????????
Screenshot 2022-10-16 at 2 08 34 PM

**Comment by lambda-makes-things** [comment]
im curious did you intend for there to be any purpose with this or was this accidental some how or like....
just what?

**Comment by Skull0025** [comment]
If you look on line 22 I changed it so the user would not think adding A restaurant request was necessary. I got this code from food-server. Also, What were you guys going to implement with this? Just curious.

**Comment by lambda-makes-things** [comment]
> If you look on line 22 I changed it so the user would not think adding A restaurant request was necessary. I got the code in reference from food-server. Also, What were you guys going to implement with this? Just curious.

line 22 on what?

**Comment by Skull0025** [comment]
Im Sorry, I meant line 32. Line 32 in the file in question in my fork.

**Comment by lambda-makes-things** [comment]
> Im Sorry, I meant line 32. Line 32 in the file in question in my fork.

sorry i still dont understand the point

**Comment by Skull0025** [comment]
Ok So I changed line 32 to say that because the default base_manage.html Would warn A user that Demae would break if no data was added. That is deceiving because if you don't put in a restaurant request demae will not break

**Comment by Skull0025** [comment]
Also Lambda What were you guys planning to implement with Restaurant Requests Anyways?

**Comment by lambda-makes-things** [comment]
> Also Lambda What were you guys planning to implement with Restaurant Requests Anyways?

At this time we wont, if we do it probably wont be in this way.

**Pull request closed without merging**
