### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lambda-makes-things**
Added Arch info and some touch ups

### CODE REVIEW

**Comment by SketchMaster2001** [comment]
Could we just make a wiki page because at this point the readme is getting a bit big imo

**Comment by lambda-makes-things** [comment]
> Could we just make a wiki page because at this point the readme is getting a bit big imo

i could work on it but i dont have any permissions to do so.

i think you would need to add me into the org @SketchMaster2001

**Comment by lambda-makes-things** [comment]
> > Could we just make a wiki page because at this point the readme is getting a bit big imo
> 
> i could work on it but i dont have any permissions to do so.
> 
> i think you would need to add me into the org @SketchMaster2001

I think there might be an option to allow outside contributors but im not sure

**Comment by spotlightishere** [comment]
> Could we just make a wiki page because at this point the readme is getting a bit big imo

Absolutely - a wiki seems like the best option. I've migrated the majority of this information to [the wiki](https://github.com/WiiLink24/food-server/wiki/Self-Hosting).

@lambda-makes-things: Please let me know if you're still unable to make edits!

@SketchMaster2001: I've enabled discussions for this repository; we'll have to work on migrating other repositories to wikis fully going forward here!

**Pull request closed without merging**
